version: '3.3'
services:
  db:
    image: postgres:11
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./chinook_data.sql
        target: /docker-entrypoint-initdb.d/chinook_data.sql
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
      POSTGRES_DB: chinook
  web:
    depends_on:
      - db
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chinook
      SPRING_DATASOURCE_USERNAME: vagrant
      SPRING_DATASOURCE_PASSWORD: vagrant

volumes:
  db_data:
